name: Issue / Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/nefino/projects/2
          github-token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          labeled: type/epic
          label-operator: NOT
